import type { LanguagePreference } from '../types';

export const languageOptions: Array<{ value: LanguagePreference; label: string; short: string }> = [
  { value: 'en', label: 'English', short: 'EN' },
  { value: 'pcm', label: 'Nigerian Pidgin', short: 'PID' },
  { value: 'yo', label: 'Yorùbá', short: 'YO' },
  { value: 'ha', label: 'Hausa', short: 'HA' },
  { value: 'ig', label: 'Igbo', short: 'IG' }
];

const semantic: Record<string, string> = {
  'nav.home': 'Overview',
  'nav.sales': 'Sales',
  'nav.inventory': 'Inventory',
  'nav.debts': 'Debts',
  'nav.settings': 'Settings',
  'greeting.morning': 'Good morning',
  'greeting.afternoon': 'Good afternoon',
  'greeting.evening': 'Good evening',
  'dashboard.eyebrow': 'BUSINESS OVERVIEW',
  'dashboard.subtitle': 'One clear view of how your business is moving.',
  'dashboard.sales': 'Sales',
  'dashboard.expenses': 'Expenses',
  'dashboard.profit': 'Profit',
  'dashboard.chartTitle': 'Business performance',
  'dashboard.chartSubtitle': 'Track sales, expenses and cash profit over time.',
  'period.weekly': 'Weekly',
  'period.monthly': 'Monthly',
  'period.yearly': 'Yearly',
  'crm.title': 'Customer CRM',
  'crm.subtitle': 'Understand customers, follow up and keep relationships organized.',
  'invoice.title': 'Invoices',
  'invoice.create': 'Create invoice',
  'receipt.view': 'Receipt',
  'language.label': 'Language',
  'language.helper': 'Choose the language OjaFlow should use across the app.'
};

type Vars = Record<string, string | number>;

const pcm: Record<string, string> = {
  'Overview': 'Overview',
  'Sales': 'Sales',
  'Inventory': 'Goods / Stock',
  'Debts': 'People Wey Owe',
  'Settings': 'Settings',
  'Good morning': 'Good morning',
  'Good afternoon': 'Good afternoon',
  'Good evening': 'Good evening',
  'BUSINESS OVERVIEW': 'YOUR BUSINESS',
  'One clear view of how your business is moving.': 'See how your business dey move for one place.',
  'Expenses': 'Money Wey Comot',
  'Profit': 'Profit',
  'Business performance': 'How business dey move',
  'Track sales, expenses and cash profit over time.': 'Check sales, expenses and profit over time.',
  'Weekly': 'This Week',
  'Monthly': 'This Month',
  'Yearly': 'This Year',
  'Customer CRM': 'Customer Records',
  'Understand customers, follow up and keep relationships organized.': 'Know your customers and follow up well.',
  'Invoices': 'Invoices',
  'Create invoice': 'Create invoice',
  'Receipt': 'Receipt',
  'Language': 'Language',
  'Choose the language OjaFlow should use across the app.': 'Choose the language wey OjaFlow go use everywhere for the app.',
  'CONTROL CENTRE': 'CONTROL CENTRE',
  'Account, security, data and preferences — without exposing private details here.': 'Manage your account, security, data and preferences here.',
  'Account': 'Account',
  'Personal Profile': 'Personal Profile',
  'Manage your personal account': 'Manage your personal account',
  'Business Profile': 'Business Profile',
  'Manage your store information': 'Manage your shop information',
  'Security & Login': 'Security & Login',
  'Password and phone security': 'Password and phone security',
  'Preferences': 'Preferences',
  'Appearance': 'Appearance',
  'Light, dark or system theme': 'Light, dark or system theme',
  'Notifications': 'Notifications',
  'Choose the alerts you want': 'Choose alerts wey you want',
  'Data': 'Data',
  'Backup & Sync': 'Backup & Sync',
  'Export My Data': 'Export My Data',
  'JSON, CSV and business summary': 'JSON, CSV and business summary',
  'Support & Legal': 'Support & Legal',
  'Help & Support': 'Help & Support',
  'FAQs and support ticket': 'FAQs and support ticket',
  'About OjaFlow': 'About OjaFlow',
  'What OjaFlow is built to do': 'Wetin OjaFlow dey help you do',
  'Privacy Policy': 'Privacy Policy',
  'Terms of Use': 'Terms of Use',
  'Session': 'Session',
  'Log Out': 'Log Out',
  'Danger Zone': 'Danger Zone',
  'Delete Account': 'Delete Account',
  'Permanent account removal': 'Delete account permanently',
  'Choose app language': 'Choose app language',
  'Changes apply immediately across OjaFlow.': 'The change go show immediately everywhere for OjaFlow.',
  'Save language': 'Save language',
  'Saving…': 'Saving…',
  'Saved': 'Saved',
  'STOCK CONTROL': 'STOCK CONTROL',
  'Know what you have, what it is worth and what needs restocking.': 'Know wetin you get, the value and wetin you need restock.',
  'Add product': 'Add product',
  'Products': 'Products',
  'Low stock': 'Low stock',
  'Retail stock value': 'Stock value',
  'Search inventory': 'Search stock',
  'Product': 'Product',
  'Stock': 'Stock',
  'Cost': 'Cost',
  'Sell': 'Sell',
  'Margin/unit': 'Profit/unit',
  'units': 'units',
  'Product name': 'Product name',
  'Category': 'Category',
  'Cost price': 'Cost price',
  'Selling price': 'Selling price',
  'Current stock': 'Current stock',
  'Low-stock level': 'Low-stock level',
  'Save product': 'Save product',
  'CREDIT CONTROL': 'CREDIT CONTROL',
  'Debts & credit': 'Debt & Credit',
  'Track who owes you and what you owe suppliers.': 'Track people wey owe you and suppliers wey you owe.',
  'Add debt': 'Add debt',
  'TOTAL OPEN BALANCE': 'TOTAL OPEN BALANCE',
  'Open': 'Open',
  'Paid': 'Paid',
  'Remaining': 'Balance',
  'Customer owes you': 'Customer owe you',
  'You owe supplier': 'You owe supplier',
  'Record payment': 'Record payment',
  'Add debt or credit': 'Add debt or credit',
  'Type': 'Type',
  'Customer owes me': 'Customer owe me',
  'I owe a supplier': 'I owe supplier',
  'Name': 'Name',
  'Phone': 'Phone',
  'Optional': 'Optional',
  'Total amount': 'Total amount',
  'Already paid': 'Already paid',
  'Due date': 'Due date',
  'Save debt': 'Save debt',
  'CUSTOMERS & MONEY FLOW': 'CUSTOMERS & MONEY FLOW',
  'Sales, CRM & invoices': 'Sales, Customers & Invoices',
  'Record transactions, understand customers and create professional documents.': 'Record transactions, know your customers and create business documents.',
  'Record sale': 'Record sale',
  'Add expense': 'Add expense',
  'Add customer': 'Add customer',
  'Search records': 'Search records',
  'Item': 'Item',
  'Customer': 'Customer',
  'Payment': 'Payment',
  'Amount': 'Amount',
  'Document': 'Document',
  'Walk-in': 'Walk-in',
  'Record a sale to generate your first professional receipt.': 'Record one sale to create your first receipt.',
  'Description': 'Description',
  'Date': 'Date',
  'Quantity': 'Quantity',
  'Unit price': 'Unit price',
  'Payment method': 'Payment method',
  'Walk-in customer': 'Walk-in customer',
  'Save sale & enable receipt': 'Save sale & create receipt',
  'Record an expense': 'Record expense',
  'Transport': 'Transport',
  'Supplies': 'Supplies',
  'Rent': 'Rent',
  'Utilities': 'Utilities',
  'Salary': 'Salary',
  'Other': 'Other',
  'Save expense': 'Save expense',
  'CURRENT BUSINESS': 'CURRENT BUSINESS',
  'WORKSPACE': 'WORKSPACE',
  'Business owner': 'Business owner',
  'Ready': 'Ready',
  'Syncing': 'Syncing',
  'Synced': 'Synced',
  'Offline': 'Offline',
  'Sync issue': 'Sync issue',
  'Quick action': 'Quick action',
  'OjaChat': 'OjaChat',
  'Copy': 'Copy',
  'Copied': 'Copied',
  'Like': 'Like',
  'Dislike': 'Dislike',
  'Thinking': 'Thinking',
  'Ask OjaChat anything…': 'Ask OjaChat anything…',
  'Store intelligence + general assistant': 'Store intelligence + general assistant',
  'Instant answers from your records, plus broader online help.': 'Quick answers from your records plus general online help.',
  'How is my business doing today?': 'How my business dey do today?',
  'Give me three practical ways to increase sales.': 'Give me three practical ways to increase sales.',
  'How should a small trader manage cash flow?': 'How small trader fit manage cash flow?',
  'Help me create a customer-retention plan.': 'Help me create plan to keep customers.',
  'TODAY\'S CASH MOVEMENT': 'TODAY CASH MOVEMENT',
  'Recorded sales minus today\'s recorded expenses.': 'Recorded sales minus money wey comot today.',
  'Gross profit estimate': 'Estimated gross profit',
  'Sales vs yesterday': 'Sales compare yesterday',
  'No prior-day baseline': 'No yesterday record to compare',
  'Yesterday': 'Yesterday',
  'Outstanding customer debt': 'Customer money outside',
  'Inventory retail value': 'Stock retail value',
  'Customers': 'Customers',
  'Low-stock items': 'Low-stock items',
  'Review debts': 'Check debts',
  'Open inventory': 'Open stock',
  'Open CRM': 'Open customers',
  'Check stock': 'Check stock',
  'Needs your attention': 'Need your attention',
  'Stock levels look healthy': 'Stock level dey okay',
  'RECENT ACTIVITY': 'RECENT ACTIVITY',
  'Latest sales': 'Latest sales',
  'View all': 'View all',
  'ATTENTION': 'ATTENTION',
  'Stock watch': 'Stock watch',
  'Your first recorded sale will appear here.': 'Your first sale go show here.',
  'No product is currently at its reorder level.': 'No product need restock now.',
  'BUSINESS SETUP': 'BUSINESS SETUP',
  'Tell us about your business': 'Tell us about your business',
  'This helps OjaFlow personalize your workspace.': 'This go help OjaFlow arrange your workspace.',
  'Business name': 'Business name',
  'Business category': 'Business category',
  'Business phone': 'Business phone',
  'Business address': 'Business address',
  'Finish setup': 'Finish setup',
  'Preparing your business workspace…': 'OjaFlow dey prepare your business workspace…',
  'Loading your profile…': 'OjaFlow dey load your profile…',
  'Preparing workspace…': 'OjaFlow dey prepare workspace…'
};

const yo: Record<string, string> = {
  'Overview': 'Àkótán',
  'Sales': 'Títà',
  'Inventory': 'Ọjà inú ṣọ́ọ̀bù',
  'Debts': 'Gbèsè',
  'Settings': 'Ètò',
  'Good morning': 'Ẹ káàárọ̀',
  'Good afternoon': 'Ẹ káàsán',
  'Good evening': 'Ẹ káalẹ́',
  'BUSINESS OVERVIEW': 'ÀKÓTÁN IṢẸ́',
  'One clear view of how your business is moving.': 'Wo bí iṣẹ́ rẹ ṣe ń lọ ní ibi kan.',
  'Expenses': 'Ìnáwó',
  'Profit': 'Èrè',
  'Business performance': 'Ìlọsíwájú iṣẹ́',
  'Track sales, expenses and cash profit over time.': 'Tẹ̀lé títà, ìnáwó àti èrè rẹ.',
  'Weekly': 'Ọ̀sẹ̀',
  'Monthly': 'Oṣù',
  'Yearly': 'Ọdún',
  'Customer CRM': 'Àkọsílẹ̀ àwọn oníbàárà',
  'Understand customers, follow up and keep relationships organized.': 'Mọ àwọn oníbàárà rẹ kí o sì tọ́jú ìbáṣepọ̀.',
  'Invoices': 'Ìwé owó',
  'Create invoice': 'Ṣẹ̀dá ìwé owó',
  'Receipt': 'Rísítì',
  'Language': 'Èdè',
  'Choose the language OjaFlow should use across the app.': 'Yan èdè tí OjaFlow yóò lò káàkiri app náà.',
  'CONTROL CENTRE': 'IBÙDÓ ÌṢÀKÓSO',
  'Account, security, data and preferences — without exposing private details here.': 'Ṣàkóso àkọọlẹ̀, ààbò, data àti àwọn ààyò rẹ.',
  'Account': 'Àkọọlẹ̀',
  'Personal Profile': 'Profaili Ara ẹni',
  'Manage your personal account': 'Ṣàkóso àkọọlẹ̀ ara ẹni rẹ',
  'Business Profile': 'Profaili Iṣòwò',
  'Manage your store information': 'Ṣàkóso ìwífún ṣọ́ọ̀bù rẹ',
  'Security & Login': 'Ààbò àti Wọlé',
  'Password and phone security': 'Ààbò ọ̀rọ̀ aṣínà àti fóònù',
  'Preferences': 'Àwọn Ààyò',
  'Appearance': 'Ìrísí',
  'Light, dark or system theme': 'Ìmọ́lẹ̀, òkùnkùn tàbí eto ẹrọ',
  'Notifications': 'Ìfitónilétí',
  'Choose the alerts you want': 'Yan ìfitónilétí tí o fẹ́',
  'Data': 'Data',
  'Backup & Sync': 'Afẹ́yinti àti Sync',
  'Export My Data': 'Gbé Data Mi Jáde',
  'JSON, CSV and business summary': 'JSON, CSV àti àkótán iṣẹ́',
  'Support & Legal': 'Ìrànlọ́wọ́ àti Òfin',
  'Help & Support': 'Ìrànlọ́wọ́',
  'FAQs and support ticket': 'Àwọn ìbéèrè àti ìrànlọ́wọ́',
  'About OjaFlow': 'Nípa OjaFlow',
  'What OjaFlow is built to do': 'Ohun tí OjaFlow ṣe',
  'Privacy Policy': 'Ìlànà Àṣírí',
  'Terms of Use': 'Àwọn Òfin Lílo',
  'Session': 'Àkókò Wọlé',
  'Log Out': 'Jáde',
  'Danger Zone': 'Agbègbè Ewu',
  'Delete Account': 'Pa Àkọọlẹ̀ Rẹ́',
  'Permanent account removal': 'Yọ àkọọlẹ̀ kúrò pátápátá',
  'Choose app language': 'Yan èdè app',
  'Changes apply immediately across OjaFlow.': 'Àyípadà yóò hàn lẹ́sẹ̀kẹsẹ̀ káàkiri OjaFlow.',
  'Save language': 'Fi èdè pamọ́',
  'Saving…': 'Ń fipamọ́…',
  'Saved': 'Ti fipamọ́',
  'STOCK CONTROL': 'ÌṢÀKÓSO ỌJÀ',
  'Know what you have, what it is worth and what needs restocking.': 'Mọ ohun tí o ní, iye rẹ̀ àti ohun tí ó yẹ kí o tún rà.',
  'Add product': 'Fi ọjà kún',
  'Products': 'Àwọn ọjà',
  'Low stock': 'Ọjà díẹ̀',
  'Retail stock value': 'Iye ọjà lórí selifu',
  'Search inventory': 'Wá nínú ọjà',
  'Product': 'Ọjà',
  'Stock': 'Ọjà tó kù',
  'Cost': 'Iye rà',
  'Sell': 'Iye tà',
  'Margin/unit': 'Èrè/kọ̀ọ̀kan',
  'units': 'ẹ̀yà',
  'Product name': 'Orúkọ ọjà',
  'Category': 'Ẹ̀ka',
  'Cost price': 'Iye rà',
  'Selling price': 'Iye tà',
  'Current stock': 'Ọjà tó wà',
  'Low-stock level': 'Ìpele ìkìlọ̀ ọjà',
  'Save product': 'Fi ọjà pamọ́',
  'CREDIT CONTROL': 'ÌṢÀKÓSO GBÈSÈ',
  'Debts & credit': 'Gbèsè àti Kirẹditi',
  'Track who owes you and what you owe suppliers.': 'Tẹ̀lé ẹni tó jẹ ọ́ ní gbèsè àti gbèsè tí o jẹ olùpèsè.',
  'Add debt': 'Fi gbèsè kún',
  'TOTAL OPEN BALANCE': 'ÀPAPỌ̀ GBÈSÈ TÓ ṢÍ',
  'Open': 'Ṣí',
  'Paid': 'Ti san',
  'Remaining': 'Tó kù',
  'Customer owes you': 'Oníbàárà jẹ ọ́ ní gbèsè',
  'You owe supplier': 'O jẹ olùpèsè ní gbèsè',
  'Record payment': 'Kọ ìsanwó sílẹ̀',
  'Add debt or credit': 'Fi gbèsè tàbí kirẹditi kún',
  'Type': 'Irú',
  'Customer owes me': 'Oníbàárà jẹ mí ní gbèsè',
  'I owe a supplier': 'Mo jẹ olùpèsè ní gbèsè',
  'Name': 'Orúkọ',
  'Phone': 'Fóònù',
  'Optional': 'Kì í ṣe dandan',
  'Total amount': 'Àpapọ̀ iye',
  'Already paid': 'Tí a ti san',
  'Due date': 'Ọjọ́ ìsanwó',
  'Save debt': 'Fi gbèsè pamọ́',
  'CUSTOMERS & MONEY FLOW': 'ONÍBÀÁRÀ ÀTI ÌṢẸ̀ OWÓ',
  'Sales, CRM & invoices': 'Títà, Oníbàárà àti Ìwé Owó',
  'Record transactions, understand customers and create professional documents.': 'Kọ ìṣòwò sílẹ̀, mọ àwọn oníbàárà, kí o sì ṣẹ̀dá ìwé iṣẹ́.',
  'Record sale': 'Kọ títà sílẹ̀',
  'Add expense': 'Fi ìnáwó kún',
  'Add customer': 'Fi oníbàárà kún',
  'Search records': 'Wá nínú àkọsílẹ̀',
  'Item': 'Ọjà',
  'Customer': 'Oníbàárà',
  'Payment': 'Ìsanwó',
  'Amount': 'Iye',
  'Document': 'Ìwé',
  'Walk-in': 'Oníbàárà tó wọlé',
  'Record a sale to generate your first professional receipt.': 'Kọ títà kan sílẹ̀ láti ṣẹ̀dá rísítì àkọ́kọ́.',
  'Description': 'Àlàyé',
  'Date': 'Ọjọ́',
  'Quantity': 'Iye ẹ̀yà',
  'Unit price': 'Iye ẹ̀yà kan',
  'Payment method': 'Ọ̀nà ìsanwó',
  'Walk-in customer': 'Oníbàárà tó wọlé',
  'Save sale & enable receipt': 'Fi títà pamọ́ kí o sì ṣẹ̀dá rísítì',
  'Record an expense': 'Kọ ìnáwó sílẹ̀',
  'Transport': 'Ọkọ̀',
  'Supplies': 'Ohun èlò',
  'Rent': 'Owó ilé',
  'Utilities': 'Iṣẹ́ ilé',
  'Salary': 'Owó oṣù',
  'Other': 'Míì',
  'Save expense': 'Fi ìnáwó pamọ́',
  'CURRENT BUSINESS': 'IṢÒWÒ LỌ́WỌ́LỌ́WỌ́',
  'WORKSPACE': 'IBI IṢẸ́',
  'Business owner': 'Olówó ìṣòwò',
  'Ready': 'Ṣetán',
  'Syncing': 'Ń sync',
  'Synced': 'Ti sync',
  'Offline': 'Kò sí íńtánẹ́ẹ̀tì',
  'Sync issue': 'Ìṣòro sync',
  'Quick action': 'Ìgbésẹ̀ kíákíá',
  'Copy': 'Daakọ',
  'Copied': 'Ti daakọ',
  'Like': 'Fẹ́ràn',
  'Dislike': 'Kò fẹ́ràn',
  'Thinking': 'Ń ronú',
  'Ask OjaChat anything…': 'Béèrè ohunkóhun lọ́wọ́ OjaChat…',
  'Store intelligence + general assistant': 'Olùrànlọ́wọ́ ìṣòwò + gbogbogbo',
  'Instant answers from your records, plus broader online help.': 'Ìdáhùn kíákíá láti inú àkọsílẹ̀ rẹ àti ìrànlọ́wọ́ gbogbogbo.',
  'How is my business doing today?': 'Báwo ni ìṣòwò mi ṣe ń lọ lónìí?',
  'Give me three practical ways to increase sales.': 'Fún mi ní ọ̀nà mẹ́ta láti pọ̀ sí títà.',
  'How should a small trader manage cash flow?': 'Báwo ni oníṣòwò kékeré ṣe lè ṣàkóso owó?',
  'Help me create a customer-retention plan.': 'Ràn mí lọ́wọ́ láti ṣe ètò láti pa àwọn oníbàárà mọ́.',
  'TODAY\'S CASH MOVEMENT': 'ÌRÌN OWÓ ÒNÍ',
  'Recorded sales minus today\'s recorded expenses.': 'Títà tí a kọ sílẹ̀ yọ ìnáwó òní kúrò.',
  'Gross profit estimate': 'Àfojúsùn èrè àpapọ̀',
  'Sales vs yesterday': 'Títà òní sí àná',
  'No prior-day baseline': 'Kò sí àkọsílẹ̀ àná fún àfiwé',
  'Yesterday': 'Àná',
  'Outstanding customer debt': 'Gbèsè oníbàárà tó kù',
  'Inventory retail value': 'Iye ọjà fún títà',
  'Customers': 'Àwọn oníbàárà',
  'Low-stock items': 'Ọjà tó kù díẹ̀',
  'Review debts': 'Ṣàyẹ̀wò gbèsè',
  'Open inventory': 'Ṣí ọjà',
  'Open CRM': 'Ṣí àkọsílẹ̀ oníbàárà',
  'Check stock': 'Ṣàyẹ̀wò ọjà',
  'Needs your attention': 'Ó nílò àkíyèsí rẹ',
  'Stock levels look healthy': 'Ipele ọjà dára',
  'RECENT ACTIVITY': 'ÌṢẸ́ TÓ ṢẸ̀ṢẸ̀',
  'Latest sales': 'Títà tuntun',
  'View all': 'Wo gbogbo rẹ',
  'ATTENTION': 'ÀKÍYÈSÍ',
  'Stock watch': 'Àbójútó ọjà',
  'Your first recorded sale will appear here.': 'Títà àkọ́kọ́ tí o kọ sílẹ̀ yóò hàn níbí.',
  'No product is currently at its reorder level.': 'Kò sí ọjà tó dé ìpele tí a gbọdọ̀ tún rà.',
  'BUSINESS SETUP': 'ÈTÒ IṢÒWÒ',
  'Tell us about your business': 'Sọ fún wa nípa ìṣòwò rẹ',
  'This helps OjaFlow personalize your workspace.': 'Èyí ń ran OjaFlow lọ́wọ́ láti ṣètò ibi iṣẹ́ rẹ.',
  'Business name': 'Orúkọ ìṣòwò',
  'Business category': 'Ẹ̀ka ìṣòwò',
  'Business phone': 'Fóònù ìṣòwò',
  'Business address': 'Àdírẹ́sì ìṣòwò',
  'Finish setup': 'Parí ètò',
  'Preparing your business workspace…': 'A ń pèsè ibi iṣẹ́ ìṣòwò rẹ…',
  'Loading your profile…': 'A ń gbé profaili rẹ wọlé…',
  'Preparing workspace…': 'A ń pèsè ibi iṣẹ́…'
};

const ha: Record<string, string> = {
  'Overview': 'Takaitawa',
  'Sales': 'Tallace-tallace',
  'Inventory': 'Kaya',
  'Debts': 'Bashi',
  'Settings': 'Saituna',
  'Good morning': 'Barka da safiya',
  'Good afternoon': 'Barka da rana',
  'Good evening': 'Barka da yamma',
  'BUSINESS OVERVIEW': 'TAKAITAWAR KASUWANCI',
  'One clear view of how your business is moving.': 'Duba yadda kasuwancinka yake tafiya a wuri guda.',
  'Expenses': 'Kashe-kashe',
  'Profit': 'Riba',
  'Business performance': 'Ayyukan kasuwanci',
  'Track sales, expenses and cash profit over time.': 'Bi diddigin tallace-tallace, kashe-kashe da riba.',
  'Weekly': 'Mako',
  'Monthly': 'Wata',
  'Yearly': 'Shekara',
  'Customer CRM': 'Bayanan abokan ciniki',
  'Understand customers, follow up and keep relationships organized.': 'San abokan cinikinka kuma ka bi su yadda ya dace.',
  'Invoices': 'Rasitan biyan kuɗi',
  'Create invoice': 'Ƙirƙiri invoice',
  'Receipt': 'Rasiti',
  'Language': 'Harshe',
  'Choose the language OjaFlow should use across the app.': 'Zaɓi harshen da OjaFlow zai yi amfani da shi a duk app ɗin.',
  'CONTROL CENTRE': 'CIBIYAR SARRAFAWA',
  'Account, security, data and preferences — without exposing private details here.': 'Sarrafa asusu, tsaro, bayanai da abubuwan da ka fi so.',
  'Account': 'Asusu',
  'Personal Profile': 'Bayanan Kai',
  'Manage your personal account': 'Sarrafa asusun ka',
  'Business Profile': 'Bayanan Kasuwanci',
  'Manage your store information': 'Sarrafa bayanan shagon ka',
  'Security & Login': 'Tsaro da Shiga',
  'Password and phone security': 'Tsaron kalmar sirri da waya',
  'Preferences': 'Zaɓuɓɓuka',
  'Appearance': 'Bayyanar App',
  'Light, dark or system theme': 'Haske, duhu ko tsarin na’ura',
  'Notifications': 'Sanarwa',
  'Choose the alerts you want': 'Zaɓi sanarwar da kake so',
  'Data': 'Bayanai',
  'Backup & Sync': 'Ajiyar Bayanai da Sync',
  'Export My Data': 'Fitar da Bayanaina',
  'JSON, CSV and business summary': 'JSON, CSV da taƙaitawar kasuwanci',
  'Support & Legal': 'Taimako da Doka',
  'Help & Support': 'Taimako',
  'FAQs and support ticket': 'Tambayoyi da tikitin taimako',
  'About OjaFlow': 'Game da OjaFlow',
  'What OjaFlow is built to do': 'Abin da OjaFlow yake yi',
  'Privacy Policy': 'Manufar Sirri',
  'Terms of Use': 'Sharuɗɗan Amfani',
  'Session': 'Zaman Shiga',
  'Log Out': 'Fita',
  'Danger Zone': 'Yankin Haɗari',
  'Delete Account': 'Share Asusu',
  'Permanent account removal': 'Cire asusu har abada',
  'Choose app language': 'Zaɓi harshen app',
  'Changes apply immediately across OjaFlow.': 'Canjin zai bayyana nan take a duk OjaFlow.',
  'Save language': 'Ajiye harshe',
  'Saving…': 'Ana ajiyewa…',
  'Saved': 'An ajiye',
  'STOCK CONTROL': 'SARRAFA KAYA',
  'Know what you have, what it is worth and what needs restocking.': 'San kayan da kake da su, ƙimarsu da abin da ya kamata a sake saya.',
  'Add product': 'Ƙara kaya',
  'Products': 'Kayayyaki',
  'Low stock': 'Kaya sun kusa ƙarewa',
  'Retail stock value': 'Darajar kaya',
  'Search inventory': 'Nemo kaya',
  'Product': 'Kaya',
  'Stock': 'Adadi',
  'Cost': 'Farashin saya',
  'Sell': 'Farashin sayarwa',
  'Margin/unit': 'Riba/kowane ɗaya',
  'units': 'guda',
  'Product name': 'Sunan kaya',
  'Category': 'Rukuni',
  'Cost price': 'Farashin saya',
  'Selling price': 'Farashin sayarwa',
  'Current stock': 'Kayan yanzu',
  'Low-stock level': 'Matakin gargaɗin kaya',
  'Save product': 'Ajiye kaya',
  'CREDIT CONTROL': 'SARRAFA BASHI',
  'Debts & credit': 'Bashi da Lamuni',
  'Track who owes you and what you owe suppliers.': 'Bi diddigin wanda yake bin ka bashi da bashin da kake bin masu kaya.',
  'Add debt': 'Ƙara bashi',
  'TOTAL OPEN BALANCE': 'JIMLAR BASHIN DA YA RAGE',
  'Open': 'A buɗe',
  'Paid': 'An biya',
  'Remaining': 'Ya rage',
  'Customer owes you': 'Abokin ciniki yana bin ka bashi',
  'You owe supplier': 'Kana bin mai kaya bashi',
  'Record payment': 'Rubuta biyan kuɗi',
  'Add debt or credit': 'Ƙara bashi ko lamuni',
  'Type': 'Nau’i',
  'Customer owes me': 'Abokin ciniki yana bina bashi',
  'I owe a supplier': 'Ina bin mai kaya bashi',
  'Name': 'Suna',
  'Phone': 'Waya',
  'Optional': 'Ba dole ba',
  'Total amount': 'Jimlar kuɗi',
  'Already paid': 'An riga an biya',
  'Due date': 'Ranar biya',
  'Save debt': 'Ajiye bashi',
  'CUSTOMERS & MONEY FLOW': 'ABOKAN CINIKI DA KUƊI',
  'Sales, CRM & invoices': 'Tallace-tallace, Abokan Ciniki da Invoice',
  'Record transactions, understand customers and create professional documents.': 'Rubuta ciniki, san abokan ciniki kuma ƙirƙiri takardun kasuwanci.',
  'Record sale': 'Rubuta tallace-tallace',
  'Add expense': 'Ƙara kashe kuɗi',
  'Add customer': 'Ƙara abokin ciniki',
  'Search records': 'Nemo bayanai',
  'Item': 'Kaya',
  'Customer': 'Abokin ciniki',
  'Payment': 'Biya',
  'Amount': 'Kuɗi',
  'Document': 'Takarda',
  'Walk-in': 'Baƙo',
  'Record a sale to generate your first professional receipt.': 'Rubuta tallace-tallace don ƙirƙirar rasiti na farko.',
  'Description': 'Bayani',
  'Date': 'Rana',
  'Quantity': 'Adadi',
  'Unit price': 'Farashin guda',
  'Payment method': 'Hanyar biya',
  'Walk-in customer': 'Abokin ciniki na wucewa',
  'Save sale & enable receipt': 'Ajiye tallace-tallace da rasiti',
  'Record an expense': 'Rubuta kashe kuɗi',
  'Transport': 'Sufuri',
  'Supplies': 'Kayayyakin aiki',
  'Rent': 'Haya',
  'Utilities': 'Ayyukan gida',
  'Salary': 'Albashi',
  'Other': 'Sauran',
  'Save expense': 'Ajiye kashe kuɗi',
  'CURRENT BUSINESS': 'KASUWANCI NA YANZU',
  'WORKSPACE': 'WURIN AIKI',
  'Business owner': 'Mai kasuwanci',
  'Ready': 'A shirye',
  'Syncing': 'Ana sync',
  'Synced': 'An sync',
  'Offline': 'Ba intanet',
  'Sync issue': 'Matsalar sync',
  'Quick action': 'Aiki mai sauri',
  'Copy': 'Kwafi',
  'Copied': 'An kwafa',
  'Like': 'So',
  'Dislike': 'Ba na so',
  'Thinking': 'Ana tunani',
  'Ask OjaChat anything…': 'Tambayi OjaChat komai…',
  'Store intelligence + general assistant': 'Mai ba da shawarar kasuwanci + na gama gari',
  'Instant answers from your records, plus broader online help.': 'Amsoshi daga bayananka tare da taimakon gama gari.',
  'How is my business doing today?': 'Yaya kasuwancina yake yau?',
  'Give me three practical ways to increase sales.': 'Ba ni hanyoyi uku na ƙara tallace-tallace.',
  'How should a small trader manage cash flow?': 'Ta yaya ƙaramin ɗan kasuwa zai sarrafa kuɗi?',
  'Help me create a customer-retention plan.': 'Taimaka min in yi shirin riƙe abokan ciniki.',
  'TODAY\'S CASH MOVEMENT': 'MOTSI NA KUƊIN YAU',
  'Recorded sales minus today\'s recorded expenses.': 'Tallace-tallacen da aka rubuta bayan an cire kashe kuɗin yau.',
  'Gross profit estimate': 'Kiyasin riba',
  'Sales vs yesterday': 'Tallace-tallace da jiya',
  'No prior-day baseline': 'Babu bayanan jiya don kwatanta',
  'Yesterday': 'Jiya',
  'Outstanding customer debt': 'Bashin abokan ciniki',
  'Inventory retail value': 'Darajar kayan sayarwa',
  'Customers': 'Abokan ciniki',
  'Low-stock items': 'Kayayyakin da suka kusa ƙarewa',
  'Review debts': 'Duba bashi',
  'Open inventory': 'Buɗe kaya',
  'Open CRM': 'Buɗe abokan ciniki',
  'Check stock': 'Duba kaya',
  'Needs your attention': 'Yana buƙatar kulawa',
  'Stock levels look healthy': 'Adadin kaya yana da kyau',
  'RECENT ACTIVITY': 'AIKIN KWANAN NAN',
  'Latest sales': 'Tallace-tallace na baya-bayan nan',
  'View all': 'Duba duka',
  'ATTENTION': 'KULAWA',
  'Stock watch': 'Kula da kaya',
  'Your first recorded sale will appear here.': 'Tallace-tallacen farko da ka rubuta zai bayyana nan.',
  'No product is currently at its reorder level.': 'Babu kaya da ya kai matakin sake siya yanzu.',
  'BUSINESS SETUP': 'SAITA KASUWANCI',
  'Tell us about your business': 'Faɗa mana game da kasuwancinka',
  'This helps OjaFlow personalize your workspace.': 'Wannan yana taimaka wa OjaFlow ya tsara wurin aikinka.',
  'Business name': 'Sunan kasuwanci',
  'Business category': 'Rukunin kasuwanci',
  'Business phone': 'Wayar kasuwanci',
  'Business address': 'Adireshin kasuwanci',
  'Finish setup': 'Kammala saiti',
  'Preparing your business workspace…': 'Ana shirya wurin kasuwancinka…',
  'Loading your profile…': 'Ana loda bayananka…',
  'Preparing workspace…': 'Ana shirya wurin aiki…'
};

const ig: Record<string, string> = {
  'Overview': 'Nchịkọta',
  'Sales': 'Ahịa',
  'Inventory': 'Ngwaahịa',
  'Debts': 'Ụgwọ',
  'Settings': 'Ntọala',
  'Good morning': 'Ụtụtụ ọma',
  'Good afternoon': 'Ehihie ọma',
  'Good evening': 'Mgbede ọma',
  'BUSINESS OVERVIEW': 'NCHỊKỌTA AZỤMAHỊA',
  'One clear view of how your business is moving.': 'Lee etu azụmahịa gị si aga n’otu ebe.',
  'Expenses': 'Mmefu',
  'Profit': 'Uru',
  'Business performance': 'Ọganihu azụmahịa',
  'Track sales, expenses and cash profit over time.': 'Soro ahịa, mmefu na uru gị n’oge.',
  'Weekly': 'Izu',
  'Monthly': 'Ọnwa',
  'Yearly': 'Afọ',
  'Customer CRM': 'Ndekọ ndị ahịa',
  'Understand customers, follow up and keep relationships organized.': 'Mara ndị ahịa gị ma lekọta mmekọrịta ha.',
  'Invoices': 'Invoice',
  'Create invoice': 'Mepụta invoice',
  'Receipt': 'Receipt',
  'Language': 'Asụsụ',
  'Choose the language OjaFlow should use across the app.': 'Họrọ asụsụ OjaFlow ga-eji n’akụkụ niile nke app.',
  'CONTROL CENTRE': 'EBE NJIKWA',
  'Account, security, data and preferences — without exposing private details here.': 'Jikwaa akaụntụ, nchekwa, data na mmasị gị.',
  'Account': 'Akaụntụ',
  'Personal Profile': 'Profaịlụ Onwe',
  'Manage your personal account': 'Jikwaa akaụntụ nke gị',
  'Business Profile': 'Profaịlụ Azụmahịa',
  'Manage your store information': 'Jikwaa ozi ụlọ ahịa gị',
  'Security & Login': 'Nchekwa na Nbanye',
  'Password and phone security': 'Nchekwa paswọọdụ na ekwentị',
  'Preferences': 'Mmasị',
  'Appearance': 'Ọdịdị',
  'Light, dark or system theme': 'Ọcha, ọchịchịrị ma ọ bụ usoro ngwaọrụ',
  'Notifications': 'Ọkwa',
  'Choose the alerts you want': 'Họrọ ọkwa ị chọrọ',
  'Data': 'Data',
  'Backup & Sync': 'Ndabere na Sync',
  'Export My Data': 'Wepụta Data M',
  'JSON, CSV and business summary': 'JSON, CSV na nchịkọta azụmahịa',
  'Support & Legal': 'Enyemaka na Iwu',
  'Help & Support': 'Enyemaka',
  'FAQs and support ticket': 'Ajụjụ na tiketi enyemaka',
  'About OjaFlow': 'Banyere OjaFlow',
  'What OjaFlow is built to do': 'Ihe OjaFlow e wuru ime',
  'Privacy Policy': 'Iwu Nzuzo',
  'Terms of Use': 'Usoro Ojiji',
  'Session': 'Oge Nbanye',
  'Log Out': 'Pụọ',
  'Danger Zone': 'Ebe Ihe Ize Ndụ',
  'Delete Account': 'Hichapụ Akaụntụ',
  'Permanent account removal': 'Hichapụ akaụntụ kpamkpam',
  'Choose app language': 'Họrọ asụsụ app',
  'Changes apply immediately across OjaFlow.': 'Mgbanwe ga-apụta ozugbo n’akụkụ niile nke OjaFlow.',
  'Save language': 'Chekwaa asụsụ',
  'Saving…': 'Na-echekwa…',
  'Saved': 'Echekwara',
  'STOCK CONTROL': 'NJIKWA NGWAỌRỤ',
  'Know what you have, what it is worth and what needs restocking.': 'Mara ihe ị nwere, ọnụ ahịa ya na ihe ịchọrọ ịzụta ọzọ.',
  'Add product': 'Tinye ngwaahịa',
  'Products': 'Ngwaahịa',
  'Low stock': 'Ngwaahịa pere mpe',
  'Retail stock value': 'Ọnụ ahịa ngwaahịa',
  'Search inventory': 'Chọọ ngwaahịa',
  'Product': 'Ngwaahịa',
  'Stock': 'Ọnụọgụ',
  'Cost': 'Ọnụ ịzụrụ',
  'Sell': 'Ọnụ ire',
  'Margin/unit': 'Uru/otu',
  'units': 'otu',
  'Product name': 'Aha ngwaahịa',
  'Category': 'Ụdị',
  'Cost price': 'Ọnụ ịzụrụ',
  'Selling price': 'Ọnụ ire',
  'Current stock': 'Ngwaahịa dị ugbu a',
  'Low-stock level': 'Ọkwa ịdọ aka ná ntị',
  'Save product': 'Chekwaa ngwaahịa',
  'CREDIT CONTROL': 'NJIKWA ỤGWỌ',
  'Debts & credit': 'Ụgwọ na Kredit',
  'Track who owes you and what you owe suppliers.': 'Soro ndị ji gị ụgwọ na ụgwọ ị ji ndị na-eweta ngwaahịa.',
  'Add debt': 'Tinye ụgwọ',
  'TOTAL OPEN BALANCE': 'MKPOKỌTA ỤGWỌ FỌDỤRỤ',
  'Open': 'Meghere',
  'Paid': 'Akwụọla',
  'Remaining': 'Fọdụrụ',
  'Customer owes you': 'Onye ahịa ji gị ụgwọ',
  'You owe supplier': 'Ị ji onye na-eweta ngwaahịa ụgwọ',
  'Record payment': 'Dekọọ ịkwụ ụgwọ',
  'Add debt or credit': 'Tinye ụgwọ ma ọ bụ kredit',
  'Type': 'Ụdị',
  'Customer owes me': 'Onye ahịa ji m ụgwọ',
  'I owe a supplier': 'M ji onye na-eweta ngwaahịa ụgwọ',
  'Name': 'Aha',
  'Phone': 'Ekwentị',
  'Optional': 'Nhọrọ',
  'Total amount': 'Mkpokọta ego',
  'Already paid': 'Akwụọla',
  'Due date': 'Ụbọchị ịkwụ ụgwọ',
  'Save debt': 'Chekwaa ụgwọ',
  'CUSTOMERS & MONEY FLOW': 'NDỊ AHỊA NA MMEBE EGO',
  'Sales, CRM & invoices': 'Ahịa, Ndị Ahịa na Invoice',
  'Record transactions, understand customers and create professional documents.': 'Dekọọ azụmahịa, mara ndị ahịa ma mepụta akwụkwọ azụmahịa.',
  'Record sale': 'Dekọọ ire',
  'Add expense': 'Tinye mmefu',
  'Add customer': 'Tinye onye ahịa',
  'Search records': 'Chọọ ndekọ',
  'Item': 'Ngwaahịa',
  'Customer': 'Onye ahịa',
  'Payment': 'Ịkwụ ụgwọ',
  'Amount': 'Ego',
  'Document': 'Akwụkwọ',
  'Walk-in': 'Onye batara',
  'Record a sale to generate your first professional receipt.': 'Dekọọ ire iji mepụta receipt mbụ gị.',
  'Description': 'Nkọwa',
  'Date': 'Ụbọchị',
  'Quantity': 'Ọnụọgụ',
  'Unit price': 'Ọnụ otu',
  'Payment method': 'Ụzọ ịkwụ ụgwọ',
  'Walk-in customer': 'Onye ahịa batara',
  'Save sale & enable receipt': 'Chekwaa ire ma mepụta receipt',
  'Record an expense': 'Dekọọ mmefu',
  'Transport': 'Ụgbọ njem',
  'Supplies': 'Ngwa ọrụ',
  'Rent': 'Ụgwọ ụlọ',
  'Utilities': 'Ọrụ ụlọ',
  'Salary': 'Ụgwọ ọnwa',
  'Other': 'Ndị ọzọ',
  'Save expense': 'Chekwaa mmefu',
  'CURRENT BUSINESS': 'AZỤMAHỊA UGBUA',
  'WORKSPACE': 'EBE ỌRỤ',
  'Business owner': 'Onye nwe azụmahịa',
  'Ready': 'Dị njikere',
  'Syncing': 'Na-sync',
  'Synced': 'E-syncala',
  'Offline': 'Enweghị ịntanetị',
  'Sync issue': 'Nsogbu sync',
  'Quick action': 'Omume ngwa ngwa',
  'Copy': 'Detuo',
  'Copied': 'Edekọrọ',
  'Like': 'Masịrị',
  'Dislike': 'Adịghị amasị',
  'Thinking': 'Na-eche echiche',
  'Ask OjaChat anything…': 'Jụọ OjaChat ihe ọ bụla…',
  'Store intelligence + general assistant': 'Onye enyemaka azụmahịa + izugbe',
  'Instant answers from your records, plus broader online help.': 'Azịza ngwa ngwa site na ndekọ gị na enyemaka izugbe.',
  'How is my business doing today?': 'Kedu ka azụmahịa m si aga taa?',
  'Give me three practical ways to increase sales.': 'Nye m ụzọ atọ m ga-eji mụbaa ahịa.',
  'How should a small trader manage cash flow?': 'Kedu ka obere onye ahịa ga-esi jikwaa ego?',
  'Help me create a customer-retention plan.': 'Nyere m aka ime atụmatụ idobe ndị ahịa.',
  'TODAY\'S CASH MOVEMENT': 'MMEBE EGO TAA',
  'Recorded sales minus today\'s recorded expenses.': 'Ahịa edere wepụ mmefu edere taa.',
  'Gross profit estimate': 'Ntụle uru',
  'Sales vs yesterday': 'Ahịa taa na ụnyaahụ',
  'No prior-day baseline': 'Enweghị ndekọ ụnyaahụ iji tụnyere',
  'Yesterday': 'Ụnyaahụ',
  'Outstanding customer debt': 'Ụgwọ ndị ahịa fọdụrụ',
  'Inventory retail value': 'Ọnụ ahịa ngwaahịa',
  'Customers': 'Ndị ahịa',
  'Low-stock items': 'Ngwaahịa pere mpe',
  'Review debts': 'Lelee ụgwọ',
  'Open inventory': 'Mepee ngwaahịa',
  'Open CRM': 'Mepee ndị ahịa',
  'Check stock': 'Lelee ngwaahịa',
  'Needs your attention': 'Ọ chọrọ nlebara anya',
  'Stock levels look healthy': 'Ọnụọgụ ngwaahịa dị mma',
  'RECENT ACTIVITY': 'OMUME ỌHỤRỤ',
  'Latest sales': 'Ahịa ọhụrụ',
  'View all': 'Lee niile',
  'ATTENTION': 'NLEBARA ANYA',
  'Stock watch': 'Nlekọta ngwaahịa',
  'Your first recorded sale will appear here.': 'Ahịa mbụ ị dere ga-apụta ebe a.',
  'No product is currently at its reorder level.': 'Ọ nweghị ngwaahịa ruru ọkwa ịzụta ọzọ ugbu a.',
  'BUSINESS SETUP': 'NHAZI AZỤMAHỊA',
  'Tell us about your business': 'Gwa anyị maka azụmahịa gị',
  'This helps OjaFlow personalize your workspace.': 'Nke a na-enyere OjaFlow aka ịhazi ebe ọrụ gị.',
  'Business name': 'Aha azụmahịa',
  'Business category': 'Ụdị azụmahịa',
  'Business phone': 'Ekwentị azụmahịa',
  'Business address': 'Adreesị azụmahịa',
  'Finish setup': 'Mechaa nhazi',
  'Preparing your business workspace…': 'Na-akwadebe ebe ọrụ azụmahịa gị…',
  'Loading your profile…': 'Na-ebunye profaịlụ gị…',
  'Preparing workspace…': 'Na-akwadebe ebe ọrụ…'
};


const pcmExtra: Record<string, string> = {
  'BUILT FOR EVERYDAY TRADE': 'BUILT FOR EVERYDAY TRADE',
  'Know your numbers.': 'Know your numbers.',
  'Run with confidence.': 'Run your business with confidence.',
  'Sales, stock, expenses, customers, debts and business guidance in one calm workspace.': 'Sales, stock, expenses, customers, debt and business advice for one place.',
  'Log in': 'Log in',
  'Create account': 'Create account',
  'WELCOME BACK': 'WELCOME BACK',
  'Continue to your business': 'Continue your business',
  'Use your registered phone number and password.': 'Use your registered phone number and password.',
  'Phone number': 'Phone number',
  'Password': 'Password',
  'Your password': 'Your password',
  'Forgot password?': 'Forget password?',
  'Signing in…': 'Signing in…',
  'NEW TO OJAFLOW?': 'NEW TO OJAFLOW?',
  'Create your trader account': 'Create your trader account',
  'No email required. Your phone number is your login ID and your password protects the account.': 'You no need email. Your phone number na your login ID and password dey protect the account.',
  'SMS verification is not required in this MVP. Double-check your phone number before creating the account.': 'SMS verification no dey for this MVP. Check your phone number well before you create account.',
  'First name': 'First name',
  'Surname': 'Surname',
  'Other name': 'Other name',
  'Confirm password': 'Confirm password',
  'Creating account…': 'Creating account…',
  'Back to login': 'Back to login',
  'ACCOUNT RECOVERY': 'ACCOUNT RECOVERY',
  'Forgot your password?': 'Forget your password?',
  'Self-service password recovery is temporarily unavailable because OjaFlow does not yet have a verified free recovery channel.': 'Password recovery no dey available for now because OjaFlow never get free verified recovery channel.',
  'If you are still signed in on another device, open Settings → Security & Login → Change Password.': 'If you still login for another device, go Settings → Security & Login → Change Password.',
  'Business command centre': 'Business command centre',
  'Private account controls': 'Private account controls',
  'OjaChat intelligent assistant': 'OjaChat intelligent assistant',
  'Nigeria-first. Trader-focused. Built to scale.': 'Nigeria-first. Trader-focused. Built to grow.',
  'General Trading': 'General Trading',
  'Food & Groceries': 'Food & Groceries',
  'Fashion': 'Fashion',
  'Electronics': 'Electronics',
  'Beauty & Personal Care': 'Beauty & Personal Care',
  'Pharmacy / Health Retail': 'Pharmacy / Health Retail',
  'Select category': 'Select category',
  'Market, town or city': 'Market, town or city',
  'What do you want to record?': 'Wetin you wan record?',
  'Money coming in': 'Money wey enter',
  'Money going out': 'Money wey comot',
  'Update your stock': 'Update your stock',
  'Across {count} open records': 'Across {count} open records',
  '{paid} paid of {total}': '{paid} paid out of {total}',
  'Call': 'Call',
  'Total amount paid so far': 'Total amount wey don pay',
  'Cash': 'Cash',
  'Transfer': 'Transfer',
  'Credit': 'Credit',
  'Open receipt': 'Open receipt',
  'Download receipt': 'Download receipt',
  'Send receipt summary on WhatsApp': 'Send receipt summary for WhatsApp',
  'Customer name': 'Customer name',
  'CRM tags': 'Customer tags',
  'Comma separated': 'Use comma separate am',
  'Customer notes': 'Customer notes',
  'Customer has agreed to receive business updates on WhatsApp': 'Customer agree make you send business updates for WhatsApp',
  'Save CRM changes': 'Save customer changes',
  'Add customers to start building your customer relationship history.': 'Add customers so you fit start keep customer history.',
  'Total spent': 'Total money spent',
  'Purchases': 'Purchases',
  'Outstanding': 'Money outside',
  'Last purchase': 'Last purchase',
  'Create professional invoice': 'Create professional invoice',
  'Select customer': 'Select customer',
  'Item / service': 'Item / service',
  'Qty': 'Qty',
  'Remove': 'Remove',
  'Add line': 'Add line',
  'Invoice total': 'Invoice total',
  'Note': 'Note',
  'Create & open invoice': 'Create & open invoice',
  'Create an invoice for a customer and it will appear here.': 'Create invoice for customer and e go show here.',
  'Print / PDF': 'Print / PDF',
  'Download': 'Download',
  'Mark paid': 'Mark paid',
  'Change Password': 'Change Password',
  'Change password': 'Change password',
  'Current password': 'Current password',
  'New password': 'New password',
  'Confirm new password': 'Confirm new password',
  'Update password': 'Update password',
  'Updating…': 'Updating…',
  'Show passwords': 'Show passwords',
  'Hide passwords': 'Hide passwords',
  'Confirm it’s you': 'Confirm say na you',
  'Enter your password before changing sensitive account information.': 'Enter your password before you change sensitive account information.',
  'Continue': 'Continue',
  'Checking…': 'Checking…',
  'Registered phone': 'Registered phone',
  'Save changes': 'Save changes',
  'Edit profile': 'Edit profile',
  'Edit business': 'Edit business',
  'Save business': 'Save business',
  'Account phone': 'Account phone',
  'Phone number changes': 'Phone number changes',
  'Changing the registered phone number is not available from the profile screen yet.': 'You no fit change registered phone number from profile screen for now.',
  'Light': 'Light',
  'Dark': 'Dark',
  'System': 'System',
  'Bright, clean workspace': 'Bright clean workspace',
  'Comfortable in low light': 'Good for low light',
  'Follow your device setting': 'Follow your device setting',
  'Low-stock alerts': 'Low-stock alerts',
  'Debt reminders': 'Debt reminders',
  'Daily business summary': 'Daily business summary',
  'Sync problems': 'Sync problems',
  'Current status': 'Current status',
  'Sync now': 'Sync now',
  'Syncing…': 'Syncing…',
  'Full JSON backup': 'Full JSON backup',
  'CSV spreadsheets': 'CSV spreadsheets',
  'Business summary': 'Business summary',
  'Still need help?': 'You still need help?',
  'Subject': 'Subject',
  'What happened?': 'Wetin happen?',
  'Submit support ticket': 'Submit support ticket',
  'Simple by design': 'Simple by design',
  'Local-first': 'Local-first',
  'Trader-aware AI': 'Trader-aware AI',
  'Privacy-conscious': 'Privacy-conscious',
  'Information OjaFlow uses': 'Information OjaFlow dey use',
  'Why the information is used': 'Why OjaFlow dey use the information',
  'Passwords and account security': 'Password and account security',
  'Exports': 'Exports',
  'Before public launch': 'Before public launch',
  'Your records': 'Your records',
  'Account security': 'Account security',
  'Service availability': 'Service availability',
  'Before commercial release': 'Before commercial release',
  'Log out': 'Log out',
  'Log out of OjaFlow?': 'Log out of OjaFlow?',
  'Cancel': 'Cancel',
  'This is permanent': 'This one permanent',
  'Enter your current password': 'Enter your current password',
  'Type this phrase exactly:': 'Type this phrase exactly:',
  'Confirmation phrase': 'Confirmation phrase',
  'I understand that this account deletion is permanent and cannot be undone.': 'I understand say this account deletion permanent and dem no fit undo am.',
  'Delete Account Permanently': 'Delete Account Permanently',
  'Deleting…': 'Deleting…',
  'Selected': 'Selected',
  'Tap to select': 'Tap to select',
  'Ask naturally': 'Ask anyhow you like',
  'OjaChat can analyse your records or answer general questions online.': 'OjaChat fit analyse your records or answer general questions online.',
  'Copy message': 'Copy message',
  'Helpful': 'Helpful',
  'Not helpful': 'Not helpful',
  'Send message': 'Send message',
  'Offline — OjaFlow record questions still work.': 'Offline — questions about your OjaFlow records still fit work.',
  'Hi. I’m OjaChat, your intelligent assistant for {business}. Ask about your OjaFlow records, business strategy, or a general question.': 'Hi. I be OjaChat, your intelligent assistant for {business}. Ask me about your OjaFlow records, business strategy or any general question.',
  'You are offline. I can still answer questions calculated from records saved in OjaFlow. General questions need an internet connection.': 'You dey offline. I still fit answer questions wey come from records saved for OjaFlow. General questions need internet.',
  'I could not reach the online assistant right now. Questions about your saved OjaFlow records may still work, or you can try again shortly.': 'I no fit reach the online assistant now. Questions about your saved OjaFlow records fit still work, or try again later.',
  'Sales Receipt': 'Sales Receipt',
  'Business': 'Business',
  'Receipt details': 'Receipt details',
  'Total paid': 'Total paid',
  'Thank you for your business.': 'Thank you for your business.',
  'Generated with OjaFlow': 'Generated with OjaFlow',
  'Invoice': 'Invoice',
  'From': 'From',
  'Bill to': 'Bill to',
  'Issued': 'Issued',
  'Due': 'Due',
  'On receipt': 'On receipt',
  'Subtotal': 'Subtotal',
  'Total': 'Total',
  'Close': 'Close',
  'Print / Save PDF': 'Print / Save PDF',
  'None': 'None'
};

const yoExtra: Record<string, string> = {
  'BUILT FOR EVERYDAY TRADE': 'A ṢE FÚN IṢÒWÒ OJOOJÚMỌ́',
  'Know your numbers.': 'Mọ àwọn nọ́mbà rẹ.',
  'Run with confidence.': 'Ṣàkóso ìṣòwò rẹ pẹ̀lú ìgboyà.',
  'Sales, stock, expenses, customers, debts and business guidance in one calm workspace.': 'Títà, ọjà, ìnáwó, oníbàárà, gbèsè àti ìmọ̀ràn ìṣòwò ní ibi kan.',
  'Log in': 'Wọlé',
  'Create account': 'Ṣẹ̀dá àkọọlẹ̀',
  'WELCOME BACK': 'KÁÀBỌ̀ PADÀ',
  'Continue to your business': 'Tẹ̀síwájú sí ìṣòwò rẹ',
  'Use your registered phone number and password.': 'Lo nọ́mbà fóònù tí o forúkọsílẹ̀ àti ọ̀rọ̀ aṣínà.',
  'Phone number': 'Nọ́mbà fóònù',
  'Password': 'Ọ̀rọ̀ aṣínà',
  'Your password': 'Ọ̀rọ̀ aṣínà rẹ',
  'Forgot password?': 'Ṣé o gbàgbé ọ̀rọ̀ aṣínà?',
  'Signing in…': 'Ń wọlé…',
  'NEW TO OJAFLOW?': 'TUNTUN SÍ OJAFLOW?',
  'Create your trader account': 'Ṣẹ̀dá àkọọlẹ̀ oníṣòwò rẹ',
  'No email required. Your phone number is your login ID and your password protects the account.': 'A kò nílò email. Nọ́mbà fóònù rẹ ni ID wọlé, ọ̀rọ̀ aṣínà sì ń dáàbò bo àkọọlẹ̀.',
  'SMS verification is not required in this MVP. Double-check your phone number before creating the account.': 'Ìmúdájú SMS kò nílò fún MVP yìí. Ṣàyẹ̀wò nọ́mbà fóònù rẹ dáadáa kí o tó ṣẹ̀dá àkọọlẹ̀.',
  'First name': 'Orúkọ àkọ́kọ́',
  'Surname': 'Orúkọ ìdílé',
  'Other name': 'Orúkọ míì',
  'Confirm password': 'Jẹ́rìí ọ̀rọ̀ aṣínà',
  'Creating account…': 'Ń ṣẹ̀dá àkọọlẹ̀…',
  'Back to login': 'Padà sí wọlé',
  'ACCOUNT RECOVERY': 'ÌGBÀPADÀ ÀKỌỌLẸ̀',
  'Forgot your password?': 'Ṣé o gbàgbé ọ̀rọ̀ aṣínà rẹ?',
  'Self-service password recovery is temporarily unavailable because OjaFlow does not yet have a verified free recovery channel.': 'Ìgbàpadà ọ̀rọ̀ aṣínà fúnra rẹ kò sí fún ìgbà díẹ̀ nítorí OjaFlow kò tíì ní ọ̀nà ìgbàpadà ọ̀fẹ́ tí a fìdí rẹ̀ múlẹ̀.',
  'If you are still signed in on another device, open Settings → Security & Login → Change Password.': 'Tí o bá ṣì wọlé lórí ẹrọ míì, lọ sí Ètò → Ààbò àti Wọlé → Yí Ọ̀rọ̀ Aṣínà Padà.',
  'Business command centre': 'Ibùdó ìṣàkóso ìṣòwò',
  'Private account controls': 'Ìṣàkóso àkọọlẹ̀ àṣírí',
  'OjaChat intelligent assistant': 'Olùrànlọ́wọ́ OjaChat',
  'Nigeria-first. Trader-focused. Built to scale.': 'Nàìjíríà ni àkọ́kọ́. A fojú sí oníṣòwò. A ṣe láti dàgbà.',
  'General Trading': 'Ìṣòwò Gbogbogbo',
  'Food & Groceries': 'Oúnjẹ àti Ọjà Ilé',
  'Fashion': 'Aṣọ',
  'Electronics': 'Ẹ̀rọ Itanna',
  'Beauty & Personal Care': 'Ẹwà àti Ìtọju Ara',
  'Pharmacy / Health Retail': 'Ile Oògùn / Ọjà Ìlera',
  'Select category': 'Yan ẹ̀ka',
  'Market, town or city': 'Ọjà, ìlú tàbí agbègbè',
  'What do you want to record?': 'Kí ni o fẹ́ kọ sílẹ̀?',
  'Money coming in': 'Owó tó ń wọlé',
  'Money going out': 'Owó tó ń jáde',
  'Update your stock': 'Ṣàfikún àkọsílẹ̀ ọjà rẹ',
  'Across {count} open records': 'Nínú àkọsílẹ̀ {count} tó ṣí',
  '{paid} paid of {total}': '{paid} ti san nínú {total}',
  'Call': 'Pe',
  'Total amount paid so far': 'Àpapọ̀ iye tí a ti san',
  'Cash': 'Owó ọwọ́',
  'Transfer': 'Ìfiránṣẹ́ owó',
  'Credit': 'Kirẹditi',
  'Open receipt': 'Ṣí rísítì',
  'Download receipt': 'Gba rísítì',
  'Send receipt summary on WhatsApp': 'Fi àkótán rísítì ránṣẹ́ lórí WhatsApp',
  'Customer name': 'Orúkọ oníbàárà',
  'CRM tags': 'Àmì CRM',
  'Comma separated': 'Fi kọ́mà yà wọ́n',
  'Customer notes': 'Àkọsílẹ̀ oníbàárà',
  'Customer has agreed to receive business updates on WhatsApp': 'Oníbàárà ti gba láti rí ìmúdójúìwọ̀n ìṣòwò lórí WhatsApp',
  'Save CRM changes': 'Fi àyípadà CRM pamọ́',
  'Add customers to start building your customer relationship history.': 'Fi àwọn oníbàárà kún láti bẹ̀rẹ̀ àkọsílẹ̀ ìbáṣepọ̀.',
  'Total spent': 'Àpapọ̀ tí a ná',
  'Purchases': 'Ríra',
  'Outstanding': 'Tó kù',
  'Last purchase': 'Ríra tó kẹ́yìn',
  'Create professional invoice': 'Ṣẹ̀dá invoice tó péye',
  'Select customer': 'Yan oníbàárà',
  'Item / service': 'Ọjà / iṣẹ́',
  'Qty': 'Iye',
  'Remove': 'Yọ',
  'Add line': 'Fi ìlà kún',
  'Invoice total': 'Àpapọ̀ invoice',
  'Note': 'Àkọsílẹ̀',
  'Create & open invoice': 'Ṣẹ̀dá kí o sì ṣí invoice',
  'Create an invoice for a customer and it will appear here.': 'Ṣẹ̀dá invoice fún oníbàárà, yóò sì hàn níbí.',
  'Print / PDF': 'Tẹ̀ / PDF',
  'Download': 'Gba sílẹ̀',
  'Mark paid': 'Ṣàmì pé a ti san',
  'Change Password': 'Yí Ọ̀rọ̀ Aṣínà Padà',
  'Change password': 'Yí ọ̀rọ̀ aṣínà padà',
  'Current password': 'Ọ̀rọ̀ aṣínà lọwọlọwọ',
  'New password': 'Ọ̀rọ̀ aṣínà tuntun',
  'Confirm new password': 'Jẹ́rìí ọ̀rọ̀ aṣínà tuntun',
  'Update password': 'Ṣàfikún ọ̀rọ̀ aṣínà',
  'Updating…': 'Ń ṣe àfikún…',
  'Show passwords': 'Fi ọ̀rọ̀ aṣínà hàn',
  'Hide passwords': 'Fi ọ̀rọ̀ aṣínà pamọ́',
  'Confirm it’s you': 'Jẹ́rìí pé ìwọ ni',
  'Enter your password before changing sensitive account information.': 'Tẹ ọ̀rọ̀ aṣínà rẹ kí o tó yí ìwífún pàtàkì padà.',
  'Continue': 'Tẹ̀síwájú',
  'Checking…': 'Ń ṣàyẹ̀wò…',
  'Registered phone': 'Fóònù tí a forúkọsílẹ̀',
  'Save changes': 'Fi àyípadà pamọ́',
  'Edit profile': 'Ṣàtúnṣe profaili',
  'Edit business': 'Ṣàtúnṣe ìṣòwò',
  'Save business': 'Fi ìṣòwò pamọ́',
  'Account phone': 'Fóònù àkọọlẹ̀',
  'Phone number changes': 'Àyípadà nọ́mbà fóònù',
  'Changing the registered phone number is not available from the profile screen yet.': 'Yíyan nọ́mbà fóònù tí a forúkọsílẹ̀ padà kò tíì sí lórí ojú profaili.',
  'Light': 'Ìmọ́lẹ̀',
  'Dark': 'Òkùnkùn',
  'System': 'Eto Ẹrọ',
  'Bright, clean workspace': 'Ibi iṣẹ́ tó mọ́, tó ní ìmọ́lẹ̀',
  'Comfortable in low light': 'Rọrùn ní ibi òkùnkùn',
  'Follow your device setting': 'Tẹ̀lé eto ẹrọ rẹ',
  'Low-stock alerts': 'Ìkìlọ̀ ọjà díẹ̀',
  'Debt reminders': 'Ìrántí gbèsè',
  'Daily business summary': 'Àkótán ìṣòwò ojoojúmọ́',
  'Sync problems': 'Ìṣòro sync',
  'Current status': 'Ipò lọwọlọwọ',
  'Sync now': 'Sync báyìí',
  'Syncing…': 'Ń sync…',
  'Full JSON backup': 'Afẹ́yinti JSON kíkún',
  'CSV spreadsheets': 'Àwọn tábìlì CSV',
  'Business summary': 'Àkótán ìṣòwò',
  'Still need help?': 'Ṣé o ṣì nílò ìrànlọ́wọ́?',
  'Subject': 'Kókó',
  'What happened?': 'Kí ló ṣẹlẹ̀?',
  'Submit support ticket': 'Fi ìbéèrè ìrànlọ́wọ́ ránṣẹ́',
  'Simple by design': 'Rọrùn ní ìmúlò',
  'Local-first': 'Àkọ́kọ́ lórí ẹrọ',
  'Trader-aware AI': 'AI tó mọ ìṣòwò',
  'Privacy-conscious': 'A bọ̀wọ̀ fún àṣírí',
  'Information OjaFlow uses': 'Ìwífún tí OjaFlow ń lò',
  'Why the information is used': 'Ìdí tí a fi ń lo ìwífún',
  'Passwords and account security': 'Ọ̀rọ̀ aṣínà àti ààbò àkọọlẹ̀',
  'Exports': 'Ìgbéjáde',
  'Before public launch': 'Kí a tó ṣe ìtusílẹ̀ fún gbogbo ènìyàn',
  'Your records': 'Àwọn àkọsílẹ̀ rẹ',
  'Account security': 'Ààbò àkọọlẹ̀',
  'Service availability': 'Wíwà iṣẹ́',
  'Before commercial release': 'Kí a tó tu síta fún ìṣòwò',
  'Log out': 'Jáde',
  'Log out of OjaFlow?': 'Jáde kúrò ní OjaFlow?',
  'Cancel': 'Fagilé',
  'This is permanent': 'Èyí jẹ́ títí láé',
  'Enter your current password': 'Tẹ ọ̀rọ̀ aṣínà lọwọlọwọ',
  'Type this phrase exactly:': 'Tẹ gbolohun yìí gẹ́gẹ́ bí ó ṣe rí:',
  'Confirmation phrase': 'Gbolohun ìmúdájú',
  'I understand that this account deletion is permanent and cannot be undone.': 'Mo lóye pé pípa àkọọlẹ̀ yìí jẹ́ títí láé, a kò sì lè dá a padà.',
  'Delete Account Permanently': 'Pa Àkọọlẹ̀ Rẹ́ Pátápátá',
  'Deleting…': 'Ń pa á…',
  'Selected': 'Ti yan',
  'Tap to select': 'Fọwọ́ kan láti yan',
  'Ask naturally': 'Béèrè lọ́nà àdáyébá',
  'OjaChat can analyse your records or answer general questions online.': 'OjaChat lè ṣàyẹ̀wò àkọsílẹ̀ rẹ tàbí dáhùn ìbéèrè gbogbogbo lórí ayelujara.',
  'Copy message': 'Daakọ ifiranṣẹ́',
  'Helpful': 'Wúlò',
  'Not helpful': 'Kò wúlò',
  'Send message': 'Fi ifiranṣẹ́ ránṣẹ́',
  'Offline — OjaFlow record questions still work.': 'Kò sí íńtánẹ́ẹ̀tì — ìbéèrè nípa àkọsílẹ̀ OjaFlow ṣì lè ṣiṣẹ́.',
  'Hi. I’m OjaChat, your intelligent assistant for {business}. Ask about your OjaFlow records, business strategy, or a general question.': 'Pẹ̀lẹ́. Èmi ni OjaChat, olùrànlọ́wọ́ rẹ fún {business}. Béèrè nípa àkọsílẹ̀ OjaFlow, ìlànà ìṣòwò tàbí ìbéèrè gbogbogbo.',
  'Sales Receipt': 'Rísítì Títà',
  'Business': 'Ìṣòwò',
  'Receipt details': 'Àlàyé rísítì',
  'Total paid': 'Àpapọ̀ tí a san',
  'Thank you for your business.': 'Ẹ ṣé fún ìṣòwò yín.',
  'Generated with OjaFlow': 'A ṣẹ̀dá pẹ̀lú OjaFlow',
  'Invoice': 'Invoice',
  'From': 'Láti ọ̀dọ̀',
  'Bill to': 'Owó sí',
  'Issued': 'Ọjọ́ tí a ṣe',
  'Due': 'Ọjọ́ ìsanwó',
  'On receipt': 'Nígbà gbigba',
  'Subtotal': 'Àpapọ̀ kékeré',
  'Total': 'Àpapọ̀',
  'Close': 'Pa',
  'Print / Save PDF': 'Tẹ̀ / Fi PDF pamọ́',
  'None': 'Kò sí'
};

const haExtra: Record<string, string> = {
  'BUILT FOR EVERYDAY TRADE': 'AN GINA DON KASUWANCI NA KULLUM',
  'Know your numbers.': 'San alkalumanka.',
  'Run with confidence.': 'Gudanar da kasuwanci da kwarin gwiwa.',
  'Sales, stock, expenses, customers, debts and business guidance in one calm workspace.': 'Tallace-tallace, kaya, kashe kuɗi, abokan ciniki, bashi da shawarar kasuwanci a wuri guda.',
  'Log in': 'Shiga',
  'Create account': 'Ƙirƙiri asusu',
  'WELCOME BACK': 'BARKA DA DAWOWA',
  'Continue to your business': 'Ci gaba zuwa kasuwancinka',
  'Use your registered phone number and password.': 'Yi amfani da lambar wayarka da kalmar sirri.',
  'Phone number': 'Lambar waya',
  'Password': 'Kalmar sirri',
  'Your password': 'Kalmar sirrinka',
  'Forgot password?': 'Ka manta kalmar sirri?',
  'Signing in…': 'Ana shiga…',
  'NEW TO OJAFLOW?': 'SABO A OJAFLOW?',
  'Create your trader account': 'Ƙirƙiri asusun ɗan kasuwarka',
  'No email required. Your phone number is your login ID and your password protects the account.': 'Ba a buƙatar email. Lambar wayarka ita ce ID ɗin shiga, kalmar sirri kuma tana kare asusun.',
  'SMS verification is not required in this MVP. Double-check your phone number before creating the account.': 'Ba a buƙatar tabbatarwar SMS a wannan MVP. Duba lambar wayarka sosai kafin ƙirƙirar asusu.',
  'First name': 'Sunan farko',
  'Surname': 'Sunan iyali',
  'Other name': 'Sauran suna',
  'Confirm password': 'Tabbatar da kalmar sirri',
  'Creating account…': 'Ana ƙirƙirar asusu…',
  'Back to login': 'Koma shiga',
  'ACCOUNT RECOVERY': 'DAWO DA ASUSU',
  'Forgot your password?': 'Ka manta kalmar sirrinka?',
  'Self-service password recovery is temporarily unavailable because OjaFlow does not yet have a verified free recovery channel.': 'Dawo da kalmar sirri da kai ba ya samuwa yanzu saboda OjaFlow bai da ingantacciyar hanyar dawo da asusu kyauta tukuna.',
  'If you are still signed in on another device, open Settings → Security & Login → Change Password.': 'Idan har yanzu kana shiga a wata na’ura, buɗe Saituna → Tsaro da Shiga → Canja Kalmar Sirri.',
  'Business command centre': 'Cibiyar sarrafa kasuwanci',
  'Private account controls': 'Sarrafa asusu cikin sirri',
  'OjaChat intelligent assistant': 'Mai taimakon OjaChat',
  'Nigeria-first. Trader-focused. Built to scale.': 'Najeriya farko. Mai da hankali ga ’yan kasuwa. An gina don girma.',
  'General Trading': 'Kasuwanci Gabaɗaya',
  'Food & Groceries': 'Abinci da Kayan Gida',
  'Fashion': 'Tufafi',
  'Electronics': 'Na’urorin Lantarki',
  'Beauty & Personal Care': 'Kwalliya da Kula da Jiki',
  'Pharmacy / Health Retail': 'Magunguna / Kayan Lafiya',
  'Select category': 'Zaɓi rukuni',
  'Market, town or city': 'Kasuwa, gari ko birni',
  'What do you want to record?': 'Me kake son rubutawa?',
  'Money coming in': 'Kuɗin shiga',
  'Money going out': 'Kuɗin fita',
  'Update your stock': 'Sabunta kayanka',
  'Across {count} open records': 'A cikin bayanai {count} da suke buɗe',
  '{paid} paid of {total}': 'An biya {paid} daga {total}',
  'Call': 'Kira',
  'Total amount paid so far': 'Jimlar da aka biya zuwa yanzu',
  'Cash': 'Tsabar kuɗi',
  'Transfer': 'Canja wurin kuɗi',
  'Credit': 'Bashi',
  'Open receipt': 'Buɗe rasiti',
  'Download receipt': 'Sauke rasiti',
  'Send receipt summary on WhatsApp': 'Aika taƙaitawar rasiti a WhatsApp',
  'Customer name': 'Sunan abokin ciniki',
  'CRM tags': 'Alamomin CRM',
  'Comma separated': 'Raba da waƙafi',
  'Customer notes': 'Bayanan abokin ciniki',
  'Customer has agreed to receive business updates on WhatsApp': 'Abokin ciniki ya yarda ya karɓi sabuntawar kasuwanci a WhatsApp',
  'Save CRM changes': 'Ajiye canjin CRM',
  'Add customers to start building your customer relationship history.': 'Ƙara abokan ciniki don fara tarihin hulɗa.',
  'Total spent': 'Jimlar kashewa',
  'Purchases': 'Siyayya',
  'Outstanding': 'Bai ƙare ba',
  'Last purchase': 'Siyayya ta ƙarshe',
  'Create professional invoice': 'Ƙirƙiri invoice na kasuwanci',
  'Select customer': 'Zaɓi abokin ciniki',
  'Item / service': 'Kaya / sabis',
  'Qty': 'Adadi',
  'Remove': 'Cire',
  'Add line': 'Ƙara layi',
  'Invoice total': 'Jimlar invoice',
  'Note': 'Bayani',
  'Create & open invoice': 'Ƙirƙiri kuma buɗe invoice',
  'Create an invoice for a customer and it will appear here.': 'Ƙirƙiri invoice ga abokin ciniki, zai bayyana nan.',
  'Print / PDF': 'Buga / PDF',
  'Download': 'Sauke',
  'Mark paid': 'Alama an biya',
  'Change Password': 'Canja Kalmar Sirri',
  'Change password': 'Canja kalmar sirri',
  'Current password': 'Kalmar sirri ta yanzu',
  'New password': 'Sabuwar kalmar sirri',
  'Confirm new password': 'Tabbatar da sabuwar kalmar sirri',
  'Update password': 'Sabunta kalmar sirri',
  'Updating…': 'Ana sabuntawa…',
  'Show passwords': 'Nuna kalmomin sirri',
  'Hide passwords': 'Ɓoye kalmomin sirri',
  'Confirm it’s you': 'Tabbatar kai ne',
  'Enter your password before changing sensitive account information.': 'Shigar da kalmar sirri kafin canza bayanan asusu masu muhimmanci.',
  'Continue': 'Ci gaba',
  'Checking…': 'Ana dubawa…',
  'Registered phone': 'Wayar da aka yi rajista',
  'Save changes': 'Ajiye canje-canje',
  'Edit profile': 'Gyara bayanai',
  'Edit business': 'Gyara kasuwanci',
  'Save business': 'Ajiye kasuwanci',
  'Account phone': 'Wayar asusu',
  'Phone number changes': 'Canjin lambar waya',
  'Changing the registered phone number is not available from the profile screen yet.': 'Ba a iya canza lambar wayar rajista daga shafin bayanai tukuna.',
  'Light': 'Haske',
  'Dark': 'Duhu',
  'System': 'Tsarin na’ura',
  'Bright, clean workspace': 'Wurin aiki mai haske',
  'Comfortable in low light': 'Mai sauƙi a duhu',
  'Follow your device setting': 'Bi saitin na’urarka',
  'Low-stock alerts': 'Gargaɗin ƙarancin kaya',
  'Debt reminders': 'Tuna bashi',
  'Daily business summary': 'Taƙaitawar kasuwanci ta kullum',
  'Sync problems': 'Matsalolin sync',
  'Current status': 'Matsayi na yanzu',
  'Sync now': 'Sync yanzu',
  'Syncing…': 'Ana sync…',
  'Full JSON backup': 'Cikakken ajiyar JSON',
  'CSV spreadsheets': 'Teburin CSV',
  'Business summary': 'Taƙaitawar kasuwanci',
  'Still need help?': 'Har yanzu kana buƙatar taimako?',
  'Subject': 'Jigo',
  'What happened?': 'Me ya faru?',
  'Submit support ticket': 'Aika tikitin taimako',
  'Simple by design': 'An tsara shi da sauƙi',
  'Local-first': 'Na’ura da farko',
  'Trader-aware AI': 'AI mai fahimtar kasuwanci',
  'Privacy-conscious': 'Mai kula da sirri',
  'Information OjaFlow uses': 'Bayanan da OjaFlow ke amfani da su',
  'Why the information is used': 'Dalilin amfani da bayanan',
  'Passwords and account security': 'Kalmar sirri da tsaron asusu',
  'Exports': 'Fitar da bayanai',
  'Before public launch': 'Kafin sakin ga jama’a',
  'Your records': 'Bayanan ka',
  'Account security': 'Tsaron asusu',
  'Service availability': 'Samuwar sabis',
  'Before commercial release': 'Kafin sakin kasuwanci',
  'Log out': 'Fita',
  'Log out of OjaFlow?': 'Fita daga OjaFlow?',
  'Cancel': 'Soke',
  'This is permanent': 'Wannan na dindindin ne',
  'Enter your current password': 'Shigar da kalmar sirri ta yanzu',
  'Type this phrase exactly:': 'Rubuta wannan jimla daidai:',
  'Confirmation phrase': 'Jimlar tabbatarwa',
  'I understand that this account deletion is permanent and cannot be undone.': 'Na fahimci cewa share wannan asusu na dindindin ne kuma ba za a iya dawo da shi ba.',
  'Delete Account Permanently': 'Share Asusu Har Abada',
  'Deleting…': 'Ana sharewa…',
  'Selected': 'An zaɓa',
  'Tap to select': 'Taɓa don zaɓa',
  'Ask naturally': 'Yi tambaya yadda kake so',
  'OjaChat can analyse your records or answer general questions online.': 'OjaChat zai iya nazarin bayananka ko amsa tambayoyi na gabaɗaya a intanet.',
  'Copy message': 'Kwafi saƙo',
  'Helpful': 'Mai amfani',
  'Not helpful': 'Ba mai amfani ba',
  'Send message': 'Aika saƙo',
  'Offline — OjaFlow record questions still work.': 'Ba intanet — tambayoyin bayanan OjaFlow har yanzu suna aiki.',
  'Hi. I’m OjaChat, your intelligent assistant for {business}. Ask about your OjaFlow records, business strategy, or a general question.': 'Sannu. Ni OjaChat ne, mai taimakonka na {business}. Tambaye ni game da bayanan OjaFlow, dabarun kasuwanci ko tambaya ta gabaɗaya.',
  'Sales Receipt': 'Rasitin Tallace-tallace',
  'Business': 'Kasuwanci',
  'Receipt details': 'Bayanan rasiti',
  'Total paid': 'Jimlar da aka biya',
  'Thank you for your business.': 'Mun gode da kasuwancinku.',
  'Generated with OjaFlow': 'An ƙirƙira da OjaFlow',
  'Invoice': 'Invoice',
  'From': 'Daga',
  'Bill to': 'Biya zuwa',
  'Issued': 'An fitar',
  'Due': 'Ranar biya',
  'On receipt': 'Da zarar an karɓa',
  'Subtotal': 'Ƙaramin jimla',
  'Total': 'Jimla',
  'Close': 'Rufe',
  'Print / Save PDF': 'Buga / Ajiye PDF',
  'None': 'Babu'
};

const igExtra: Record<string, string> = {
  'BUILT FOR EVERYDAY TRADE': 'E WURU YA MAKA AZỤMAHỊA KWA ỤBỌCHỊ',
  'Know your numbers.': 'Mara ọnụọgụ gị.',
  'Run with confidence.': 'Jikwaa azụmahịa gị n’obi ike.',
  'Sales, stock, expenses, customers, debts and business guidance in one calm workspace.': 'Ahịa, ngwaahịa, mmefu, ndị ahịa, ụgwọ na ndụmọdụ azụmahịa n’otu ebe.',
  'Log in': 'Banye',
  'Create account': 'Mepụta akaụntụ',
  'WELCOME BACK': 'NNOỌ LAGHACHI',
  'Continue to your business': 'Gaa n’ihu na azụmahịa gị',
  'Use your registered phone number and password.': 'Jiri nọmba ekwentị edebanyere na paswọọdụ gị.',
  'Phone number': 'Nọmba ekwentị',
  'Password': 'Paswọọdụ',
  'Your password': 'Paswọọdụ gị',
  'Forgot password?': 'Chefuru paswọọdụ?',
  'Signing in…': 'Na-abanye…',
  'NEW TO OJAFLOW?': 'ỌHỤRỤ NA OJAFLOW?',
  'Create your trader account': 'Mepụta akaụntụ onye ahịa gị',
  'No email required. Your phone number is your login ID and your password protects the account.': 'Email adịghị mkpa. Nọmba ekwentị gị bụ ID nbanye, paswọọdụ gị na-echekwa akaụntụ.',
  'SMS verification is not required in this MVP. Double-check your phone number before creating the account.': 'Nkwenye SMS adịghị mkpa na MVP a. Lelee nọmba ekwentị gị nke ọma tupu ịmepụta akaụntụ.',
  'First name': 'Aha mbụ',
  'Surname': 'Aha ezinụlọ',
  'Other name': 'Aha ọzọ',
  'Confirm password': 'Kwenye paswọọdụ',
  'Creating account…': 'Na-emepụta akaụntụ…',
  'Back to login': 'Laghachi na nbanye',
  'ACCOUNT RECOVERY': 'WEGHACHITE AKAỤNTỤ',
  'Forgot your password?': 'Chefuru paswọọdụ gị?',
  'Self-service password recovery is temporarily unavailable because OjaFlow does not yet have a verified free recovery channel.': 'Iweghachite paswọọdụ n’onwe gị adịghị ugbu a n’ihi na OjaFlow enwebeghị ụzọ nkwenye efu.',
  'If you are still signed in on another device, open Settings → Security & Login → Change Password.': 'Ọ bụrụ na ị ka banye na ngwaọrụ ọzọ, gaa Ntọala → Nchekwa na Nbanye → Gbanwee Paswọọdụ.',
  'Business command centre': 'Ebe njikwa azụmahịa',
  'Private account controls': 'Njikwa akaụntụ nzuzo',
  'OjaChat intelligent assistant': 'Onye enyemaka OjaChat',
  'Nigeria-first. Trader-focused. Built to scale.': 'Naịjirịa mbụ. Maka ndị ahịa. E wuru ka ọ too.',
  'General Trading': 'Azụmahịa Izugbe',
  'Food & Groceries': 'Nri na Ngwaahịa Ụlọ',
  'Fashion': 'Ejiji',
  'Electronics': 'Ngwa Eletrọnik',
  'Beauty & Personal Care': 'Mma na Nlekọta Ahụ',
  'Pharmacy / Health Retail': 'Ọgwụ / Ngwa Ahụike',
  'Select category': 'Họrọ ụdị',
  'Market, town or city': 'Ahịa, obodo nta ma ọ bụ obodo',
  'What do you want to record?': 'Gịnị ka ịchọrọ idekọ?',
  'Money coming in': 'Ego na-abata',
  'Money going out': 'Ego na-apụ',
  'Update your stock': 'Melite ngwaahịa gị',
  'Across {count} open records': 'N’ime ndekọ {count} mepere',
  '{paid} paid of {total}': 'Akwụgoro {paid} n’ime {total}',
  'Call': 'Kpọọ',
  'Total amount paid so far': 'Mkpokọta ego akwụgoro',
  'Cash': 'Ego aka',
  'Transfer': 'Nyefe ego',
  'Credit': 'Kredit',
  'Open receipt': 'Mepee receipt',
  'Download receipt': 'Budata receipt',
  'Send receipt summary on WhatsApp': 'Ziga nchịkọta receipt na WhatsApp',
  'Customer name': 'Aha onye ahịa',
  'CRM tags': 'Akara CRM',
  'Comma separated': 'Kewaa na kọma',
  'Customer notes': 'Ndetu onye ahịa',
  'Customer has agreed to receive business updates on WhatsApp': 'Onye ahịa ekwenyela ịnata ozi azụmahịa na WhatsApp',
  'Save CRM changes': 'Chekwaa mgbanwe CRM',
  'Add customers to start building your customer relationship history.': 'Tinye ndị ahịa ka ịmalite ndekọ mmekọrịta.',
  'Total spent': 'Mkpokọta e mefuru',
  'Purchases': 'Ịzụrụ ihe',
  'Outstanding': 'Fọdụrụ',
  'Last purchase': 'Ịzụrụ ikpeazụ',
  'Create professional invoice': 'Mepụta invoice azụmahịa',
  'Select customer': 'Họrọ onye ahịa',
  'Item / service': 'Ngwaahịa / ọrụ',
  'Qty': 'Ọnụọgụ',
  'Remove': 'Wepụ',
  'Add line': 'Tinye ahịrị',
  'Invoice total': 'Mkpokọta invoice',
  'Note': 'Ndetu',
  'Create & open invoice': 'Mepụta ma mepee invoice',
  'Create an invoice for a customer and it will appear here.': 'Mepụta invoice maka onye ahịa, ọ ga-apụta ebe a.',
  'Print / PDF': 'Bipụta / PDF',
  'Download': 'Budata',
  'Mark paid': 'Kaa na akwụgoro',
  'Change Password': 'Gbanwee Paswọọdụ',
  'Change password': 'Gbanwee paswọọdụ',
  'Current password': 'Paswọọdụ ugbu a',
  'New password': 'Paswọọdụ ọhụrụ',
  'Confirm new password': 'Kwenye paswọọdụ ọhụrụ',
  'Update password': 'Melite paswọọdụ',
  'Updating…': 'Na-emelite…',
  'Show passwords': 'Gosi paswọọdụ',
  'Hide passwords': 'Zoo paswọọdụ',
  'Confirm it’s you': 'Kwenye na ọ bụ gị',
  'Enter your password before changing sensitive account information.': 'Tinye paswọọdụ tupu ịgbanwe ozi akaụntụ dị mkpa.',
  'Continue': 'Gaa n’ihu',
  'Checking…': 'Na-enyocha…',
  'Registered phone': 'Ekwentị edebanyere',
  'Save changes': 'Chekwaa mgbanwe',
  'Edit profile': 'Dezie profaịlụ',
  'Edit business': 'Dezie azụmahịa',
  'Save business': 'Chekwaa azụmahịa',
  'Account phone': 'Ekwentị akaụntụ',
  'Phone number changes': 'Mgbanwe nọmba ekwentị',
  'Changing the registered phone number is not available from the profile screen yet.': 'Ịgbanwe nọmba ekwentị edebanyere adịghị na profaịlụ ugbu a.',
  'Light': 'Ọcha',
  'Dark': 'Ọchịchịrị',
  'System': 'Usoro ngwaọrụ',
  'Bright, clean workspace': 'Ebe ọrụ na-egbuke egbuke',
  'Comfortable in low light': 'Dabara n’ebe ọchịchịrị',
  'Follow your device setting': 'Soro ntọala ngwaọrụ gị',
  'Low-stock alerts': 'Ọkwa ngwaahịa pere mpe',
  'Debt reminders': 'Ncheta ụgwọ',
  'Daily business summary': 'Nchịkọta azụmahịa kwa ụbọchị',
  'Sync problems': 'Nsogbu sync',
  'Current status': 'Ọnọdụ ugbu a',
  'Sync now': 'Sync ugbu a',
  'Syncing…': 'Na-sync…',
  'Full JSON backup': 'Ndabere JSON zuru ezu',
  'CSV spreadsheets': 'Tebụl CSV',
  'Business summary': 'Nchịkọta azụmahịa',
  'Still need help?': 'Ka chọrọ enyemaka?',
  'Subject': 'Isiokwu',
  'What happened?': 'Gịnị mere?',
  'Submit support ticket': 'Zipu tiketi enyemaka',
  'Simple by design': 'A haziri ya nfe',
  'Local-first': 'Ngwaọrụ mbụ',
  'Trader-aware AI': 'AI na-aghọta azụmahịa',
  'Privacy-conscious': 'Na-echekwa nzuzo',
  'Information OjaFlow uses': 'Ozi OjaFlow na-eji',
  'Why the information is used': 'Ihe kpatara eji ozi ahụ',
  'Passwords and account security': 'Paswọọdụ na nchekwa akaụntụ',
  'Exports': 'Mbupụ data',
  'Before public launch': 'Tupu ewepụta ya n’ihu ọha',
  'Your records': 'Ndekọ gị',
  'Account security': 'Nchekwa akaụntụ',
  'Service availability': 'Nnweta ọrụ',
  'Before commercial release': 'Tupu ntọhapụ azụmahịa',
  'Log out': 'Pụọ',
  'Log out of OjaFlow?': 'Pụọ na OjaFlow?',
  'Cancel': 'Kagbuo',
  'This is permanent': 'Nke a bụ nke na-adịgide adịgide',
  'Enter your current password': 'Tinye paswọọdụ gị ugbu a',
  'Type this phrase exactly:': 'Dee ahịrịokwu a kpọmkwem:',
  'Confirmation phrase': 'Ahịrịokwu nkwenye',
  'I understand that this account deletion is permanent and cannot be undone.': 'Aghọtara m na ihichapụ akaụntụ a bụ nke na-adịgide adịgide ma enweghị ike iweghachi ya.',
  'Delete Account Permanently': 'Hichapụ Akaụntụ Kpamkpam',
  'Deleting…': 'Na-ehichapụ…',
  'Selected': 'Ahọpụtara',
  'Tap to select': 'Pịa ka ịhọrọ',
  'Ask naturally': 'Jụọ n’ụzọ nkịtị',
  'OjaChat can analyse your records or answer general questions online.': 'OjaChat nwere ike nyochaa ndekọ gị ma ọ bụ zaa ajụjụ izugbe n’ịntanetị.',
  'Copy message': 'Detuo ozi',
  'Helpful': 'Bara uru',
  'Not helpful': 'Abaghị uru',
  'Send message': 'Zipu ozi',
  'Offline — OjaFlow record questions still work.': 'Enweghị ịntanetị — ajụjụ gbasara ndekọ OjaFlow ka na-arụ ọrụ.',
  'Hi. I’m OjaChat, your intelligent assistant for {business}. Ask about your OjaFlow records, business strategy, or a general question.': 'Ndewo. Abụ m OjaChat, onye enyemaka gị maka {business}. Jụọ maka ndekọ OjaFlow, atụmatụ azụmahịa ma ọ bụ ajụjụ izugbe.',
  'Sales Receipt': 'Receipt Ahịa',
  'Business': 'Azụmahịa',
  'Receipt details': 'Nkọwa receipt',
  'Total paid': 'Mkpokọta akwụgoro',
  'Thank you for your business.': 'Daalụ maka azụmahịa gị.',
  'Generated with OjaFlow': 'Emeputara na OjaFlow',
  'Invoice': 'Invoice',
  'From': 'Site na',
  'Bill to': 'Kwụọ nye',
  'Issued': 'E wepụtara',
  'Due': 'Ụbọchị ịkwụ',
  'On receipt': 'Mgbe enwetara',
  'Subtotal': 'Mkpokọta obere',
  'Total': 'Mkpokọta',
  'Close': 'Mechie',
  'Print / Save PDF': 'Bipụta / Chekwaa PDF',
  'None': 'Ọ dịghị'
};

const dictionaries: Record<LanguagePreference, Record<string, string>> = {
  en: {},
  pcm: { ...pcm, ...pcmExtra },
  yo: { ...yo, ...yoExtra },
  ha: { ...ha, ...haExtra },
  ig: { ...ig, ...igExtra }
};

function interpolate(template: string, vars?: Vars) {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_match, name: string) => String(vars[name] ?? `{${name}}`));
}

export function t(language: LanguagePreference | undefined, key: string, vars?: Vars) {
  const selected = language || 'en';
  const source = semantic[key] || key;
  const translated = selected === 'en' ? source : dictionaries[selected]?.[source] || source;
  return interpolate(translated, vars);
}

export function languageLabel(language: LanguagePreference | undefined) {
  return languageOptions.find(option => option.value === (language || 'en'))?.label || 'English';
}

export function localeForLanguage(language: LanguagePreference | undefined) {
  if (language === 'yo') return 'yo-NG';
  if (language === 'ha') return 'ha-NG';
  if (language === 'ig') return 'ig-NG';
  return 'en-NG';
}

export function languageName(language: LanguagePreference | undefined) {
  if (language === 'pcm') return 'Nigerian Pidgin';
  if (language === 'yo') return 'Yorùbá';
  if (language === 'ha') return 'Hausa';
  if (language === 'ig') return 'Igbo';
  return 'English';
}
